#
# Makefile for src/testscripts (test driver tools)
#

TOP=..
.include "$(TOP)/mk/os161.config.mk"

SCRIPTDIR=/testscripts
EXECSCRIPTS=test.py
NONEXECSCRIPTS=runtest.py

.include "$(TOP)/mk/os161.script.mk"
